#.travis.yml

language: node_js
node_js:
  - "6.9.5"

branches:
  only:
  - master
dist: trusty
node_js:
  - "6.9.5"
before_script:
  - npm install -g @angular/cli

script:
  - ng test --single-run
  - ng build

notifications:
  email:
    on_failure: change
    on_success: change
