#.travis.yml

language: node_js

node_js:
  - "6.9.5"

branches:
  only:
  - master

dist: trusty

node_js:
  - "6.9.5"

install:
  - npm install

script:
  - npm run test:coverage:single-run
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run build

notifications:
  email:
    on_failure: change
    on_success: change
