kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: endorsement-frontend-master
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: endorsement
        role: frontend
        env: master
    spec:
      containers:
      - name: frontend
        image: threece/endorsement-frontend
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        ports:
        - name: frontend
          containerPort: 8080

-----

kind: Service
apiVersion: v1
metadata:
  name: endorsement-frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: endorsement
    role: frontend
